name: Trigger auto deployment for hackathon-kemenkeu-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - '**'
    - '.github/workflows/hackathon-kemenkeu-fe-AutoDeployTrigger-29443ae6-ed3f-4eab-812f-4cab7b2b5cf3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HACKATHONKEMENKEUFE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HACKATHONKEMENKEUFE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HACKATHONKEMENKEUFE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: nawainternal.azurecr.io
          registryUsername: ${{ secrets.HACKATHONKEMENKEUFE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HACKATHONKEMENKEUFE_REGISTRY_PASSWORD }}
          containerAppName: hackathon-kemenkeu-fe
          resourceGroup: NAWA-RESEARCH-DEVELOPMENT
          imageToBuild: nawainternal.azurecr.io/hackathon-kemenkeu-fe:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


